app:
  name: "staff-service-api"
  port: 8082
  version: "1.0.0"
  env: "dev"

auth:
  serviceId: "my-service"
  clientId: "my-client"
  clientSecret: "${CLIENT_SECRET}"
  keycloakUrl: "http://auth-service:8080"
  realm: "my-realm"
  cacheEnabled: true
  cacheUrl: "redis:6379"
  resources:
  # Staff endpoints
  - path: "/api/v1/account/staff"
    method: "POST"
    roles: ["ADMIN", "ORG_CREATOR"]
    actions: ["create:staff"]

  - path: "/api/v1/account/staff"
    method: "GET"  
    roles: ["ADMIN", "ORG_ADMIN", "USER"]
    actions: ["read:staff"]

  - path: "/api/v1/account/staff/:id"
    method: "GET"
    roles: ["ADMIN", "ORG_ADMIN", "USER"]
    actions: ["read:staff"]

  - path: "/api/v1/account/staff/:id"
    method: "PUT"
    roles: ["ADMIN", "ORG_ADMIN"] 
    actions: ["update:staff"]

  - path: "/api/v1/account/staff/:id"
    method: "DELETE"
    roles: ["ADMIN"]
    actions: ["delete:staff"]

  # User endpoints
  - path: "/api/v1/account/user"
    method: "POST"
    roles: ["ADMIN", "ORG_CREATOR"]
    actions: ["create:user"]

  - path: "/api/v1/account/user"
    method: "GET"  
    roles: ["ADMIN", "ORG_ADMIN", "USER"]
    actions: ["read:user"]

  - path: "/api/v1/account/user/:id"
    method: "GET"
    roles: ["ADMIN", "ORG_ADMIN", "USER"]
    actions: ["read:user"]

  - path: "/api/v1/account/user/:id"
    method: "PUT"
    roles: ["ADMIN", "ORG_ADMIN"] 
    actions: ["update:user"]

  - path: "/api/v1/account/user/:id"
    method: "DELETE"
    roles: ["ADMIN"]
    actions: ["delete:user"]

  publicPaths:
  - path: "/health"
    method: "GET"
  # Temporary public paths until auth is implemented
  - path: "/api/v1/account//staff"
    method: "POST"
  - path: "/api/v1/account/staff"
    method: "GET"
  - path: "/api/v1/account/staff/*"
    method: "GET"
  - path: "/api/v1/account/staff/*"
    method: "PUT"
  - path: "/api/v1/account/staff/:id"
    method: "DELETE"
  - path: "/api/v1/account//user"
    method: "POST"
  - path: "/api/v1/account/user"
    method: "GET"
  - path: "/api/v1/account/user/*"
    method: "GET"
  - path: "/api/v1/account/user/*"
    method: "PUT"
  - path: "/api/v1/account/user/:id"
    method: "DELETE"

database:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "microservice-template"
  sslmode: "disable"
  max_conns: 10
  timeout: 30

logging:
  level: "info"
  format: "json"